---
- hosts: devstack
  gather_facts: False
  vars:
    devstack_repo: git://github.com/openstack-dev/devstack.git
    branch: master
    offline: no
    reclone: no
    git_base: git://github.com
    image_url: http://download.cirros-cloud.net/0.3.1/cirros-0.3.1-x86_64-uec.tar.gz
    devstack_branch: "{{branch}}"
  tasks:
    - name: git
      apt: pkg=git state=present

    - name: checkout devstack
      sudo: no
      git: repo={{devstack_repo}} dest=/home/vagrant/devstack version={{devstack_branch}} accept_hostkey=yes

    - name: copy local.conf
      sudo: no
      template: src=local.conf.full dest=/home/vagrant/devstack/local.conf

    - name: do what you like
      sudo: yes
      script: dowhatyoulike.sh

    - name: stack.sh
      sudo: no
      shell: /home/vagrant/devstack/stack.sh 2>&1 > /tmp/stack.sh.log
